[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"


[functions]
  external_node_modules = ["express", "mongoose", "bcryptjs", "jsonwebtoken"]
  node_bundler = "esbuild"



# SPA fallback - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
